stages:
  - build
  - test
  - publish

build-job:
  stage: build
  image: node:16
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
      - out

test-job-unit:
  stage: test
  dependencies: [build-job]
  image: node:16
  script:
    - npm test

test-job-lint:
  stage: test
  dependencies: [build-job]
  image: node:16
  script:
    - npm run lint

publish-job-npm:
  stage: publish
  rules:
    - if: $CI_PROJECT_NAMESPACE == "goodrouter" && $CI_COMMIT_TAG =~ /^v/
  image: node:16
  dependencies: [build-job]
  script:
    - npm version $CI_COMMIT_TAG
    - npm publish
