include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node:18
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
      - out

test-unit:
  stage: test
  dependencies: [build]
  image: node:18
  script:
    - npm run coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

test-lint:
  stage: test
  dependencies: [build]
  image: node:18
  script:
    - npm run lint

test-audit:
  stage: test
  image: node:18
  script:
    - npm audit

publish-npm:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v/
  image: node:18
  dependencies: [build]
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
    - npm version $CI_COMMIT_TAG
    - npm publish
