stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: node:16
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
      - out

test-job-unit:
  stage: test
  dependencies: [build-job]
  image: node:16
  script:
    - npm test

test-job-lint:
  stage: test
  dependencies: [build-job]
  image: node:16
  script:
    - npm run lint

deploy-job-npm:
  stage: deploy
  rules:
    - if: $CI_PROJECT_NAMESPACE == "goodrouter" && $CI_COMMIT_TAG =~ /^v/
  image: node:16
  dependencies: [build-job]
  script:
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
    - npm version $CI_COMMIT_TAG
    - npm publish
