include:
  - template: Jobs/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node:18
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
      - out

test-unit:
  stage: test
  dependencies: [build]
  image: node:18
  script:
    - npm test

test-lint:
  stage: test
  dependencies: [build]
  image: node:18
  script:
    - npm run lint

publish-npm:
  stage: publish
  rules:
    - if: $CI_COMMIT_REF_PROTECTED && $CI_COMMIT_TAG =~ /^v/
  image: node:18
  dependencies: [build]
  script:
    - npm version $CI_COMMIT_TAG
    - npm publish
