on: 
  - push
  - pull_request

jobs:

  test-unit:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  test-lint:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  test-audit:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm audit

  publish-npm:
    runs-on: ubuntu-latest
    container: node:18
    needs:
      - test-unit
      - test-lint
      - test-audit
    if: >
      github.ref_type == 'tag' && startsWith( github.ref_name, 'v' )
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm ci
      - run: npm version $GITHUB_REF_NAME
      - run: npm publish

  publish-cloudflare:
    runs-on: ubuntu-latest
    container: node:18
    needs:
      - test-unit
      - test-lint
      - test-audit
    if: >
      github.ref_type == 'tag' && startsWith( github.ref_name, 'v' )
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run docs
      - run: >
          npx wrangler pages publish ./docs
          --commit-dirty=true
          --project-name $(basename $GITHUB_REPOSITORY)
          --branch main
